server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true       # H2 콘솔 활성화
      path: /h2-console   # 접속 경로 설정 (기본: /h2-console)

logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.type: trace